### PR TITLE
bump plugin to support ES v6.8.6

### PR DESCRIPTION
**Pull request by jcantrill**
Bump Plugin to work with ES v6.8.6

blocks https://github.com/opendistro-for-elasticsearch/security/pull/190

### CODE REVIEW

**Comment by jcantrill** [comment]
@allenyin96 @hardik-k-shah  any interest in supporting later 6.8 version?

**Comment by hardik-k-shah** [comment]
Hey @jcantrill , we can do support 6.8.6. Can you please make similar changes and raise PRs for [security-parent](https://github.com/opendistro-for-elasticsearch/security-parent) and [security-kibana-plugin](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin)

Please also post result for UT runs. 

Thanks

**Comment by jcantrill** [comment]
@hardik-k-shah I modified to use v0.10.0.4 of the parent but i dont see any needed changes there to make this repo build.  Does it still need a bump?

The UT results where one failing test for a lib that I don't have installed in my dev environment.
```
2020-02-17T09:42:09,021][INFO ][o.e.n.Node               ] closing ...
[2020-02-17T09:42:09,021][INFO ][o.e.n.Node               ] closed
[ERROR] Tests run: 26, Failures: 1, Errors: 0, Skipped: 17, Time elapsed: 48.97 s <<< FAILURE! - in com.amazon.opendistroforelasticsearch.security.ssl.OpenSSLTest
[ERROR] testEnsureOpenSSLAvailability(com.amazon.opendistroforelasticsearch.security.ssl.OpenSSLTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: OpenSSL not available: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
	at com.amazon.opendistroforelasticsearch.security.ssl.OpenSSLTest.testEnsureOpenSSLAvailability(OpenSSLTest.java:69)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenSSLTest.testEnsureOpenSSLAvailability:69 OpenSSL not available: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
[INFO] 
[ERROR] Tests run: 53, Failures: 1, Errors: 0, Skipped: 18
```

**Comment by sujithvm** [comment]
@jcantrill Thank you for your contribution.

**Pull request merged**
